version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile/Dockerfile.cuda
    volumes:
      - ./:/app/
    working_dir: /app
    ports:
      - 8888:8888
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
